from pydantic import BaseModel, Field


from typing import Any

class ToolResult(BaseModel):
    """Result returned by a Tool after executing business logic."""
    success: bool
    message: str
    data: dict[str, Any] = Field(default_factory=dict)
    refresh: list[str] = Field(default_factory=list)

class ExecutionPlan(BaseModel):
    """Structured execution plan generated by the Planner Engine.

    Fields
    ------
    intent:          Detected intent name.
    steps:           Ordered list of execution steps.
    ui_action:       The UI action to dispatch (maps to ActionRenderer).
    tool:            The backend tool that handles this plan.
    entities:        Extracted + memory-enriched entities.
    session_id:      The session under which this plan was generated.
    memory_enriched: True if session memory contributed entity values
                     (e.g. pronoun resolution resolved "him" → "Rahul").
    tool_result:     Optional execution result attached by ToolRouter.
    """

    intent: str
    steps: list[str]
    ui_action: str
    tool: str
    entities: dict = Field(default_factory=dict)
    session_id: str | None = None
    memory_enriched: bool = False
    tool_result: ToolResult | None = None


class ClarificationResponse(BaseModel):
    """Returned by the Catalyst Brain when information is missing."""
    status: str = "needs_clarification"
    question: str
    intent: str = "needs_clarification"
    ui_action: str = "ask_clarification"
    tool: str = "brain"
    steps: list[str] = []
    missing_fields: list[str] = Field(default_factory=list)
